### ISSUE TITLE
Get Selected Text

### ISSUE THREAD

**Issue by mishraaditya595** [psuzn/WheelView#10]
Hey @psuzn, is their a way to get the selected text?

**Comment by RabiusRaju** [comment]
any Update ?

**Comment by RabiusRaju** [comment]
Hey, @mishraaditya595 add this code.

wheelView.setSelectListener(new Function1<Integer, Unit>() {
            @Override
            public Unit invoke(Integer integer) {
                showToast(integer);
                return Unit.INSTANCE;
            }
            private void showToast(Integer index){
                Toast.makeText(MainActivity.this, ""+wheelView.getTitles().get(index), Toast.LENGTH_SHORT).show();
            }
        });
