### ISSUE TITLE
Kotlin setOnClickListener using method reference not working

### ISSUE THREAD

**Issue by rayastar** [psuzn/WheelView#4]
Hey, hi. This code doesn't work:

```
wheelView.setOnClickListener {view ->
            Log.d("TAG","test")
        }
```
Can you fix this?

**Comment by psuzn** [comment]
All the click events inside the WheelView are consumed by it that's why you are not getting the callback.

**Comment by psuzn** [comment]
A flag to disable user input mode might be useful if you don't want to use the user's input and control the wheel's behavior from code.
