### ISSUE TITLE
Can`t get the selected item title

### ISSUE THREAD

**Issue by Tamir198** [psuzn/WheelView#5]
I am using WheelView like this:

```java

  final WheelView wheelView= view.findViewById(R.id.wheel_view);
        List<String> myList = new ArrayList<>();
        myList.add("test");
        myList.add("test2");
        myList.add("test3");
        myList.add("test4");
        wheelView.setTitles(myList);

        wheelView.getSelectListener();

        wheelView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                wheelView.getSelectListener();
            }
        });

```

Inside `wheelView.setOnClickListener` I want to get the selected Item, how can this be done?

**Comment by psuzn** [comment]
I presume you need selected arc (i.e. selected arc), you can do it like so:

```kotlin
     val titles = listOf("First", "Second", "Third", "Fourth")
     wheelView.titles = titles
     wheelView.selectListener = { // selected position
            Toast.makeText(this,"selected on ${titles[it]}",Toast.LENGTH_SHORT).show()
        }
```
If you want literal click on view (android's default click event), first you need to disable user's input by setting ```app:userInputMode="false"``` in xml.

**Comment by Tamir198** [comment]
Is this library only supporting kotlin or can I use it with java?

**Comment by psuzn** [comment]
You can use it with java too.

**Comment by Tamir198** [comment]
Could you give me an example of how can I do it with java?
I have tried but could not succeed

**Comment by psuzn** [comment]
```java
List<String> titles = Arrays.asList("First", "Second", "Third", "Fourth");
wheelView.setTitles(titles);
wheelView.setSelectListener(index -> {
    Toast.makeText(JavaActivity.this,"selected "+titles.get(index),Toast.LENGTH_SHORT).show();
    return Unit.INSTANCE;
});
```
For some reason if you are not using Java  8

```java
List<String> titles = Arrays.asList("First", "Second", "Third", "Fourth");
wheelView.setTitles(titles);
wheelView.setSelectListener(new Function1<Integer, Unit>() {
    @Override
    public Unit invoke(Integer index) {
        Toast.makeText(JavaActivity.this,"selected "+titles.get(index),Toast.LENGTH_SHORT).show();
        return Unit.INSTANCE;
    }
});
```

**Comment by Tamir198** [comment]
> ```java
> List<String> titles = Arrays.asList("First", "Second", "Third", "Fourth");
> wheelView.setTitles(titles);
> wheelView.setSelectListener(index -> {
>     Toast.makeText(JavaActivity.this,"selected "+titles.get(index),Toast.LENGTH_SHORT).show();
>     return Unit.INSTANCE;
> });
> ```
> 
> For some reason if you are not using Java 8
> 
> ```java
> List<String> titles = Arrays.asList("First", "Second", "Third", "Fourth");
> wheelView.setTitles(titles);
> wheelView.setSelectListener(new Function1<Integer, Unit>() {
>     @Override
>     public Unit invoke(Integer index) {
>         Toast.makeText(JavaActivity.this,"selected "+titles.get(index),Toast.LENGTH_SHORT).show();
>         return Unit.INSTANCE;
>     }
> });
> ```

Thank you, nice explanation.
