### ISSUE TITLE
Icon with text

### ISSUE THREAD

**Issue by fahad-mukhtar** [psuzn/WheelView#6]
Hi, is there any way we can add icon with text and make the text orientation vertical instead of horizontal. Actually I want to achieve this view. Is there anyway that your library can help me or you can suggest some other solution to achieve this view. Thanks
![horoscope](https://user-images.githubusercontent.com/52396272/97836061-48e1e700-1cfd-11eb-8d60-248faad1e885.png)

**Comment by psuzn** [comment]
Hey, currently there is no way to do it, If you want to add this feature yourself, you can look into [`WheelView.kt`](https://github.com/psuzn/WheelView/blob/master/WheelView/src/main/java/me/sujanpoudel/wheelview/WheelView.kt) and modify it a bit to add support for icons and text orientation. I'm happy to review PR.
