### ISSUE TITLE
selected index

### ISSUE THREAD

**Issue by fahad-mukhtar** [psuzn/WheelView#7]
Hi thanks for the quick response, can you please tell how to get the selected index, because I'm not able to get selected index, and also tell me how can i set nothing selected by default. Thanks

**Comment by psuzn** [comment]
you can use  `selectListener: ((Int) -> Unit)?` to get the selelected index.

```kotlin

  wheelView.selectListner = {
     Log.d("tag","selected index is $it")
}
```
To select nothing you can set `focusedIndex` to a large value : 

```kotlin

  wheelView.focusedIndex = Int.MAX_VALUE

```
Also, please continue on the same issue rather than creating a new one if things are related.
